### ISSUE TITLE
PHP minimum version and composer

### ISSUE THREAD

**Issue by BassemN** [andrastoth/FastSpeedIpLocator#1]
Hi,

Great class :)
What is the minimum PHP version? Does it support 5.3
Also are you planning to add composer support?
Thanks

**Comment by andrastoth** [comment]
Hi,
Thank you!

So, the minimum PHP version is 5.3. =>  config php - "password_verify" 
if (isset($this->users[$name]) && password_verify($pass, $this->users[$name]['password'])) {

If you replace password_verify, 
if (isset($this->users[$name]) && $pass == $this->users[$name]['password']) {
minimum PHP version is 4

Currently I do not planing composer support.

Regards,

András

**Comment by BassemN** [comment]
@andrastoth Than you very much :)
